admin_controllers:
    resource:
        path: ../src/Admin/Controller/
        namespace: App\Admin\Controller
    type: attribute

api_controllers:
    resource:
        path: ../src/Api/Controller/
        namespace: App\Api\Controller
    type: attribute

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

